### PR TITLE
Fix the build with MSVC 15.9

### PR DESCRIPTION
**Pull request by mdouaihy**
* Upgrade GooleTest from 1.8.0 to 1.8.1 to get the fixes related to the lastest MSVC 15.9 .
* Avoid redefining noexcept if MSVC version is MSVC 15.9 ( _MSC_VER is at least 1900). (https://github.com/jbeder/yaml-cpp/commit/0f9a586ca1dc29c2ecb8dd715a315b93e3f40f79#diff-ba7996b8b0eda7de7855d4cbd5a11393)

### CODE REVIEW

**Comment by ruslo** [comment]
> Upgrade GooleTest from 1.8.0 to 1.8.1 to get the fixes related to the lastest MSVC 15.9 .

Tests are not necessary and as far as I can see are excluded:
- https://github.com/ruslo/hunter/blob/v0.23.172/cmake/projects/yaml-cpp/hunter.cmake#L54-L59

**Comment by ruslo** [comment]
I've created branch `hunter-0.6.2-0f9a586` with https://github.com/jbeder/yaml-cpp/commit/0f9a586ca1dc29c2ecb8dd715a315b93e3f40f79 change:
- https://github.com/hunter-packages/yaml-cpp/tree/hunter-0.6.2-0f9a586

Please send there patches from the previous branch:
- https://github.com/hunter-packages/yaml-cpp/commits/hunter-0.6.2

Also note that there is no `HunterGate`/`hunter_add_package` added, so you can send the fixes upstream so we don't have to maintain the fork.

Details:
- https://docs.hunter.sh/en/latest/creating-new/patch.html

**Review by ruslo — CHANGES_REQUESTED** [review]
> Conflicting files

**Comment by mdouaihy** [comment]
hello @ruslo, I rebased my branch on top of hunter-0.6.2-0f9a586. Shouldn't this latter branch be rebased on top of hunter-0.6.2?

**Comment by mdouaihy** [comment]
Also, for the GTest files, what do you suggest? Should I revert any change concerning the tests?

**Comment by ruslo** [comment]
> Shouldn't this latter branch be rebased on top of hunter-0.6.2?

Not sure I understand what you mean, but the approach for creating branches described here:
- https://docs.hunter.sh/en/latest/creating-new/patch.html

`hunter-0.6.2-0f9a586` means branch started from `0f9a586` upstream tag, `0f9a586` is an additional to `0.6.2` upstream tag.

> Should I revert any change concerning the tests?

Yes, please revert, we don't need them. It will only cause conflicts in future versions.

**Comment by mdouaihy** [comment]
I reverted the changes of GTest. But in this case, there is nothing more to integrate since the first part is already integrated with this commit. https://github.com/hunter-packages/yaml-cpp/commit/0f9a586ca1dc29c2ecb8dd715a315b93e3f40f79

I will close the PR.

**Comment by ruslo** [comment]
> But in this case, there is nothing more to integrate

As far as I understand we need these patches from the previous version:
- https://github.com/hunter-packages/yaml-cpp/commit/562aefc114938e388457e6a531ed7b54d9dc1b62
- https://github.com/hunter-packages/yaml-cpp/commit/975ac34cc617c43e74ec767cef97dfa07c13b651

**Comment by mdouaihy** [comment]
Those commits are mot needed to compile on MSVC.

Shall we integrate them on hunter-0.6.2-0f9a586?

**Comment by ruslo** [comment]
> Those commits are mot needed to compile on MSVC.

They are about CMake, so they needed when you generate Visual Studio project.

> Shall we integrate them on hunter-0.6.2-0f9a586?

Yes, please send a pull request with these patches. Also please [test them](https://docs.hunter.sh/en/latest/creating-new/patch.html).

**Comment by mdouaihy** [comment]
I am not the author of theses changes so I don't know what was the problem and what need to be tested. Does anyone have this information?

Note that when I built locally on my Windows machine, I didnt get any error. Is that sufficient for you?

**Comment by ruslo** [comment]
> I am not the author of theses changes so I don't know what was the problem and what need to be tested. Does anyone have this information?

I think it's a fix for the CMake imported targets.

> Note that when I built locally on my Windows machine, I didnt get any error. Is that sufficient for you?

How you're building? Are you using `jenkins.py` testing script used in Hunter CI:
- https://docs.hunter.sh/en/latest/creating-new/create/cmake.html#testing-locally

?

**Pull request closed without merging**
